server:
  port: 8081
  
spring:  data:    mongodb:      host: ${MONGO_HOST:localhost}
      port: ${MONGO_PORT:27017}
      database: ${MONGO_DATABASE:ecommerce}
      
#spring.kafka.bootstrap-servers: localhost:9092
#spring.kafka.consumer.group-id: myGroup

kafka.bootstrapAddress: localhost:9092